{% set name = "pyoccad" %}
{% set version = "0.4.2" %}
{% set pypi_version = "0.4.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ pypi_version }}.tar.gz
  sha256: 19119009dbf29a1c46b2d8fa472e12b84f067ece641da7d3c6278e9b7baf5a38

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.7
    - pip
    - pythonocc-core >=7.4
  run:
    - python >=3.7
    - pythonocc-core >=7.4
    - numpy >=1.14
    - scipy

test:
  imports:
    - pyoccad

about:
  home: https://gitlab.com/cosapp/pyoccad
  summary: A geometrical modeler based on Open-Cascade
  description: A geometrical modeler based on the wrapping of `occt` (OpenCascade) open-source CAD package and helpers for a simplified use
  keywords: pyoccad, occt, opencascade
  dev_url: https://gitlab.com/cosapp/pyoccad 
  license_file: LICENSE
  license: Apache-2.0

extra:
  recipe-maintainers:
    - adriendelsalle
    - trungleduc
    - elac-safran
