{% set name = "pyoccad" %}
{% set version = "0.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://gitlab.com/cosapp/pyoccad/-/archive/v{{ version }}/pyoccad-v{{ version }}.tar.gz
  sha256: 1ac6608a0bf45c3eb8330d51e77a6d9c27320665db4d38425d8cac8e76d91c88

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.7
    - pip
    - pythonocc-core >=7.6
  run:
    - python >=3.7
    - pythonocc-core >=7.6
    - numpy >=1.14
    - scipy

test:
  imports:
    - pyoccad

about:
  home: https://gitlab.com/cosapp/pyoccad
  summary: A geometrical modeler based on Open-Cascade
  description: A geometrical modeler based on the wrapping of `occt` (OpenCascade) open-source CAD package and helpers for a simplified use
  keywords: pyoccad, occt, opencascade
  dev_url: https://gitlab.com/cosapp/pyoccad 
  license_file: LICENSE
  license: Apache-2.0

extra:
  recipe-maintainers:
    - adriendelsalle
    - trungleduc
    - elac-safran
